### ISSUE TITLE
Program Page Q's

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/hot-summit-2016#17]
Going off the [current schedule](https://docs.google.com/spreadsheets/d/1rCRAK62q9FWdH19N5sR2GBxbxvii9rXGuBHnSBy4WVg/edit#gid=0), it looks like the event will be fairly straightforward. All in one day, and only diverging for breakout sessions.

Here's an unstyled wireframe of what I'll be putting together. Beneath it I have a few questions regarding the schedule's content that may change a few things, but the overall framework should remain consistent.

![desktop hd](https://cloud.githubusercontent.com/assets/9341928/17192356/0f11c40e-541c-11e6-84af-f6eb273ed01b.png)
- Do you know the locations of the breakout sessions? Along the same lines, are the main events all going to occur in the same location? If there's not a specified room for the main events, I'll add an additional line to help clarify that.
- How long are the talk descriptions? It'd be amazing if they're under 100 words.
- Does the (6) next to lightning talks refer to the number of speakers, or length of the talks? Are they going to be talks with titles and descriptions I should plan for as well?

Thanks!

**Comment by smit1678** [comment]
Nice! Answers below...

> Do you know the locations of the breakout sessions? Along the same lines, are the main events all going to occur in the same location? If there's not a specified room for the main events, I'll add an additional line to help clarify that.

Yes, there will be two rooms: a larger main room for keynotes, lightning talks, and breakout session will happen; and a small room for breakout sessions. There is also a reception area where the community experience will be. I don't know the names offhand at the moment but can drop those in, or @bgirardot can as well. 

> How long are the talk descriptions? It'd be amazing if they're under 100 words.

👍 We can help cut them down. 

> Does the (6) next to lightning talks refer to the number of speakers, or length of the talks? 

Yes, each lightning talk session will have 6 talks of 5 mins each. 

> Are they going to be talks with titles and descriptions I should plan for as well?

Yes. Open to how you want to handle that, could be just a side page with a list. Similar to how State of the Map US did with the workshops.

**Comment by bgirardot** [comment]
I think it looks very nice.

Somewhere I would like to put the speaker's Bio's as well, maybe a separate page that lists the speakers, focuses on their bio's and just lists the talk they are giving

Plenary sessions and one of the breakout rooms is called: Tanganyika Conference Room
The other breakout room is: Thac Ba meeting room
