### ISSUE TITLE
Outdoor pictures

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hot-summit-2016#20]
Hi @DylanMoriarty @bgirardot could we add some outdoor photos of "maps in action" or at least people with printed maps on the homepage? Right now we're heavily skewed toward indoor events/conference photos, making the event perhaps less compelling to drive our registration #s up. If we need to remove existing ones I would suggest the santa hats or one of the other conference photos.

You can grab some good ones here: https://drive.google.com/folderview?id=0B4sFanf1NkBEMXpYcU1tUEoyOWs&usp=sharing

**Comment by bgirardot** [comment]
Uploaded some new images for the carousel on the main page.
