### ISSUE TITLE
Logo to be added

### ISSUE THREAD

**Issue by KatjaUlbert** [hotosm/hot-summit-2016#5]
![hotsummit2016_logo](https://cloud.githubusercontent.com/assets/12475465/15338807/c89a835c-1c81-11e6-8631-f627d339baaa.png)
![hotsummit2016_logo](https://cloud.githubusercontent.com/assets/12475465/15338808/c89e04aa-1c81-11e6-8ffd-a16f920518ca.jpg)

**Comment by DylanMoriarty** [comment]
Logo added many moons ago.
